.PHONY: clean All

All:
	@echo "==========Building project:[ SESION3_EJEMPLO13 - Debug ]=========="
	@cd "SESION3_EJEMPLO13" && "$(MAKE)" -f  "SESION3_EJEMPLO13.mk"
clean:
	@echo "==========Cleaning project:[ SESION3_EJEMPLO13 - Debug ]----------"
	@cd "SESION3_EJEMPLO13" && "$(MAKE)" -f  "SESION3_EJEMPLO13.mk" clean
