.PHONY: clean All

All:
	@echo "==========Building project:[ SESION1_EJEMPLO1 - Debug ]=========="
	@cd "SESION1_EJEMPLO1" && "$(MAKE)" -f  "SESION1_EJEMPLO1.mk"
clean:
	@echo "==========Cleaning project:[ SESION1_EJEMPLO1 - Debug ]----------"
	@cd "SESION1_EJEMPLO1" && "$(MAKE)" -f  "SESION1_EJEMPLO1.mk" clean
